### ISSUE TITLE
Are name properties on Markup nodes or hyperedges?

### ISSUE THREAD

**Issue by djbpitt** [djbpitt/balisage_2017#8]
I don't think there's an informational difference, and both make sense (well, to me) in different ways. I'd suggest that we go with whatever Alexandria does, unless there's a difference that I'm overlooking that might dictate otherwise.

**Comment by rhdekker** [comment]
Name properties are stored on the nodes. It is better to store as much information as possible on the nodes rather than on the edges. The nodes represent things, while edges only represent connections between the things. Properties on edges in graph modelling usually only consists of types or a weight to rate a certain path through the network.

**Comment by djbpitt** [comment]
Review text to ensure that it conforms to Ronald's clarification.

**Comment by djbpitt** [comment]
Revised text to clarify that Markup nodes may have `name` properties, but Markup-to-Text hyperedges don't.
